# file-worker .travis.yml

language: java

cache:
  directories:
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'
  
jdk:
    - openjdk11

addons:
  sonarcloud:
    organization: "lightblueseas"
    token:
      secure: $SONAR_TOKEN # encrypted value of your token

notifications:
    email:
        recipients:
            - asterios.raptis@web.de
        on_failure: always
        
after_success:
  - if [ -e ./gradlew ]; then ./gradlew jacocoTestReport;else gradle jacocoTestReport;fi
  - bash <(curl -s https://codecov.io/bash)  
  - ./gradlew sonarqube
