# file-worker .travis.yml
before_install:
  - chmod +x gradlew
language: java

cache:
  directories:
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'
  
jdk:
    - openjdk11

notifications:
    email:
        recipients:
            - asterios.raptis@web.de
        on_failure: always
        
after_success:
  - if [ -e ./gradlew ]; then ./gradlew jacocoTestReport;else gradle jacocoTestReport;fi
  - bash <(curl -s https://codecov.io/bash)
